version: '3.1'
services:
  db:
    image: mysql:8
    container_name: my-mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - ./volume/schema.sql:/docker-entrypoint-initdb.d/schema.sql